// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArticleCatalog: typeof import('./src/components/component/ArticleCatalog.vue')['default']
    ArticleListCard: typeof import('./src/components/component/ArticleListCard.vue')['default']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    BlogCard: typeof import('./src/components/component/BlogCard.vue')['default']
    Comment: typeof import('./src/components/component/Comment.vue')['default']
    HeaderCover: typeof import('./src/components/component/HeaderCover.vue')['default']
    HomeCover: typeof import('./src/components/component/HomeCover.vue')['default']
    HomeToolBar: typeof import('./src/components/component/HomeToolBar.vue')['default']
    MessageModal: typeof import('./src/components/modal/MessageModal.vue')['default']
    OauthLogin: typeof import('./src/components/component/OauthLogin.vue')['default']
    ReplayModal: typeof import('./src/components/modal/ReplayModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/modal/SearchModal.vue')['default']
    Typewriter: typeof import('./src/components/tool/Typewriter.vue')['default']
    UserModal: typeof import('./src/components/modal/UserModal.vue')['default']
  }
}

export {}
